# Generated by Django 4.1.7 on 2023-04-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='Project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Project'},
        ),
    ]
