# Generated by Django 4.1.7 on 2023-04-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.FileField(blank=True, null=True, upload_to='video/%y'),
        ),
    ]
