# Generated by Django 4.2 on 2023-04-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='project',
            name='featured_video',
            field=models.FileField(default="The user doesn't upload video file for this project", upload_to='video/%y'),
            preserve_default=False,
        ),
    ]
