# Generated by Django 4.2 on 2023-04-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y'),
        ),
    ]
