# Generated by Django 4.2 on 2023-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_featured_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_video',
            field=models.FileField(default="The use doesn't upload video file", upload_to='video/%y'),
            preserve_default=False,
        ),
    ]
